### ISSUE TITLE
vet upstream

### ISSUE THREAD

**Issue by jgreidy** [cul-it/ci-jenkins-pantheon-wordpress#186]
Warning: require(/code/vendor/composer/../symfony/polyfill-php83/bootstrap.php): Failed to open stream: No such file or directory in /code/vendor/composer/autoload_real.php on line 45

Fatal error: Uncaught Error: Failed opening required '/code/vendor/composer/../symfony/polyfill-php83/bootstrap.php' (include_path='/code/vendor/pear/archive_tar:/code/vendor/pear/console_getopt:/code/vendor/pear/pear-core-minimal/src:/code/vendor/pear/pear_exception:.:/usr/share/pear:/usr/share/php') in /code/vendor/composer/autoload_real.php:45
Stack trace:
#0 /code/vendor/composer/autoload_real.php(49): {closure}('662a729f963d39a...', '/code/vendor/co...')
#1 /code/vendor/autoload.php(25): ComposerAutoloaderInitf285205b923b34a0f33a902c527e9b3d::getLoader()
#2 /code/web/wp-config.php(15): require_once('/code/vendor/au...')
#3 /code/web/wp/wp-load.php(55): require_once('/code/web/wp-co...')
#4 /code/web/wp/wp-blog-header.php(13): require_once('/code/web/wp/wp...')
#5 /code/web/index.php(6): require('/code/web/wp/wp...')
#6 {main}
  thrown in /code/vendor/composer/autoload_real.php on line 45

**Comment by jgreidy** [comment]
https://getupstream-uls-vet-library-cornell-edu.pantheonsite.io/
